name: Pull Request Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  label:
    name: Label Pull Request
    runs-on: ubuntu-latest
    # Only run on PRs from the same repository (not forks)
    if: github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
      - name: Label PR
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: false