name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run build
        run: pnpm turbo run build
      
      - name: Run tests
        run: pnpm turbo run test -- --run
      
      - name: Publish packages to npm
        run: |
          # Extract package name from tag (e.g., v1.0.0-hook-common -> hook-common)
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          PACKAGE_SUFFIX="${TAG_NAME#*-}"
          
          if [[ "$PACKAGE_SUFFIX" == "$TAG_NAME" ]]; then
            echo "Publishing all packages with version $TAG_NAME"
            pnpm -r publish --access public --no-git-checks
          else
            echo "Publishing @civic/$PACKAGE_SUFFIX"
            cd "packages/$PACKAGE_SUFFIX"
            pnpm publish --access public --no-git-checks
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            - See commit history for details
          draft: false
          prerelease: false